from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Optional


class FoodForecastEngine:
    """Lightweight read-only deployment engine.

    It serves the final forecasts that were already generated by the validated
    2019-2025 deployment models. TensorFlow and statsmodels are intentionally
    not loaded on the public web service, which keeps RAM usage low and makes
    free-tier deployment practical.
    """

    def __init__(self, base_dir: str | Path | None = None, max_horizon: int = 36):
        self.base_dir = Path(base_dir or Path(__file__).resolve().parent).resolve()
        self.max_horizon = max_horizon

        self.data_path = self.base_dir / "model_ready_pangan_semarang_2019_2025.csv"
        self.forecast_path = self.base_dir / "forecast_champion_2026_2028.csv"
        self.metadata_path = self.base_dir / "deployment_metadata_2019_2025.json"

        for path in (self.data_path, self.forecast_path, self.metadata_path):
            if not path.exists():
                raise FileNotFoundError(f"File deployment tidak ditemukan: {path}")

        with self.metadata_path.open("r", encoding="utf-8") as f:
            self.metadata = json.load(f)

        self.selected_models = dict(self.metadata["selected_models"])
        self.validation_smape = {
            key: float(value) for key, value in self.metadata["validation_smape"].items()
        }
        self.commodities = sorted(self.selected_models)

        self._historical_rows = self._load_historical()
        self._forecast_rows = self._load_forecast()

        dates = [row["tanggal"] for row in self._historical_rows]
        self.first_observed_date = min(dates)
        self.last_observed_date = max(dates)

    def _load_historical(self):
        rows = []
        with self.data_path.open("r", encoding="utf-8-sig", newline="") as f:
            for row in csv.DictReader(f):
                commodity = row["komoditas"].strip()
                if commodity not in self.selected_models:
                    continue
                date = row["tanggal"].strip()
                rows.append(
                    {
                        "tanggal": date,
                        "komoditas": commodity,
                        "nilai": float(row["nilai"]),
                        "satuan": (row.get("satuan") or "Ton").strip() or "Ton",
                    }
                )
        rows.sort(key=lambda x: (x["komoditas"], x["tanggal"]))
        return rows

    def _load_forecast(self):
        rows = []
        with self.forecast_path.open("r", encoding="utf-8-sig", newline="") as f:
            for row in csv.DictReader(f):
                commodity = row["komoditas"].strip()
                if commodity not in self.selected_models:
                    continue
                rows.append(
                    {
                        "tanggal": row["tanggal"].strip(),
                        "komoditas": commodity,
                        "model": row["model"].strip(),
                        "horizon_bulan": int(row["horizon_bulan"]),
                        "prediksi_ketersediaan": float(row["prediksi_ketersediaan"]),
                        "satuan": (row.get("satuan") or "Ton").strip() or "Ton",
                        "validation_sMAPE_pct": float(row["validation_sMAPE_pct"]),
                    }
                )
        rows.sort(key=lambda x: (x["komoditas"], x["horizon_bulan"]))
        return rows

    @staticmethod
    def _reliability(smape: float) -> str:
        if smape <= 15:
            return "tinggi"
        if smape <= 30:
            return "sedang"
        return "rendah"

    def _validate_commodity(self, commodity: str):
        if commodity not in self.selected_models:
            valid = ", ".join(self.commodities)
            raise ValueError(f"Komoditas '{commodity}' tidak tersedia. Pilihan: {valid}")

    def _validate_horizon(self, horizon: int):
        if not isinstance(horizon, int):
            raise ValueError("Horizon harus berupa integer.")
        if horizon < 1:
            raise ValueError("Horizon minimal 1 bulan.")
        if horizon > self.max_horizon:
            raise ValueError(f"Horizon maksimal {self.max_horizon} bulan.")

    def list_commodities(self):
        result = []
        for commodity in self.commodities:
            smape = self.validation_smape[commodity]
            result.append(
                {
                    "komoditas": commodity,
                    "model": self.selected_models[commodity],
                    "validation_sMAPE_pct": smape,
                    "reliabilitas": self._reliability(smape),
                }
            )
        return result

    def historical(self, commodity: str, limit: Optional[int] = None):
        self._validate_commodity(commodity)
        rows = [r for r in self._historical_rows if r["komoditas"] == commodity]
        if limit is not None:
            rows = rows[-int(limit):]

        output = []
        for row in rows:
            year = int(row["tanggal"][:4])
            status = "historis" if year <= 2024 else "proyeksi_resmi" if year == 2025 else "lainnya"
            output.append(
                {
                    "tanggal": row["tanggal"],
                    "nilai": row["nilai"],
                    "satuan": row["satuan"],
                    "status_data": status,
                }
            )
        return output

    def forecast(self, commodity: str, horizon: int = 12):
        self._validate_commodity(commodity)
        self._validate_horizon(horizon)

        source = [
            row
            for row in self._forecast_rows
            if row["komoditas"] == commodity and row["horizon_bulan"] <= horizon
        ]
        source.sort(key=lambda x: x["horizon_bulan"])
        if len(source) != horizon:
            raise ValueError(
                f"Forecast tersimpan untuk {commodity} tidak lengkap pada horizon {horizon} bulan."
            )

        smape = self.validation_smape[commodity]
        reliability = self._reliability(smape)

        forecast_rows = [
            {
                "horizon_bulan": row["horizon_bulan"],
                "tanggal": row["tanggal"],
                "prediksi_ketersediaan": round(row["prediksi_ketersediaan"], 3),
                "satuan": row["satuan"],
                "status_data": "forecast_model",
            }
            for row in source
        ]

        return {
            "komoditas": commodity,
            "model": self.selected_models[commodity],
            "horizon": horizon,
            "periode_data": {
                "awal": self.first_observed_date,
                "historis_akhir": "2024-12-01",
                "proyeksi_resmi_2025_akhir": "2025-12-01",
            },
            "forecast_mulai": forecast_rows[0]["tanggal"],
            "validation_sMAPE_pct": round(smape, 4),
            "reliabilitas": reliability,
            "peringatan": (
                "Prediksi memiliki reliabilitas rendah berdasarkan validation sMAPE."
                if reliability == "rendah"
                else None
            ),
            "forecast": forecast_rows,
        }

    def forecast_all(self, horizon: int = 12):
        self._validate_horizon(horizon)
        return [self.forecast(commodity, horizon) for commodity in self.commodities]

    def info(self):
        return {
            "nama": "Sistem Prediksi Ketersediaan Stok Pangan Kota Semarang",
            "target": "ketersediaan pangan",
            "periode": {
                "historis": "2019-01-01 s.d. 2024-12-01",
                "proyeksi_resmi": "2025-01-01 s.d. 2025-12-01",
                "forecast_model_mulai": "2026-01-01",
            },
            "jumlah_komoditas": len(self.commodities),
            "maksimum_horizon_bulan": self.max_horizon,
            "komoditas": self.list_commodities(),
            "mode_deployment": "precomputed_final_forecast",
            "catatan": (
                "Data 2025 diperlakukan sebagai proyeksi ketersediaan resmi, bukan realisasi aktual. "
                "Forecast 2026-2028 telah dihitung sebelumnya menggunakan model deployment final "
                "dan disajikan ulang oleh web service ringan untuk hosting publik."
            ),
        }
